template: Hello, %s!
defaultName: Stranger

server:
  applicationConnectors:
  - type: http
    port: 9595
  adminConnectors:
  - type: http
    port: 9596

# Logging settings.
logging:

  # The default level of all loggers. Can be OFF, ERROR, WARN, INFO, DEBUG, TRACE, or ALL.
  level: INFO

  # Logger-specific levels.
  loggers:

    # Overrides the level of com.example.dw.Thing and sets it to DEBUG.
    "ch.ipt": DEBUG